---
title: "Visual Analysis of US Broadband Disparities"
output: html_document
references:
  - id: fingas
    title: Microsoft Says the Rural Broadband Divide Is Worse than You Think
    author: 
    - family: Fingas
      given: Jon
    container-title: Engadget
    URL: "https://www.engadget.com/2018/12/05/microsoft-study-on-rural-broadband-shortfall/"
    type: article
    issued:
      year: 2018
  
  - id: kang
    title: How to Give Rural America Broadband? Look to the Early 1900s
    author: 
    - family: Kang
      given: Cecilia
    container-title: The New York Times
    URL: "https://www.nytimes.com/2016/08/08/technology/how-to-give-rural-america-broadband-look-to-the-early-1900s.html"
    type: article
    issued:
      year: 2017
      
  - id: lenz
    title: "Iowa: Rural Broadband, and the Unknown Costs of the Digital Divide"
    author: 
    - family: Lenz
      given: Lyz
    container-title: Colombia Journalism Review
    URL: "https://www.cjr.org/special_report/midterms-2018-iowa-rural-broadband.php/"
    type: article
    issued:
      year: 2018
---

## Background

As online services and devices become increasingly ingrained and necessary in our lives in the modern world, the Internet infrastructure and service providers that connect our devices to these online services has become increasingly important as well. Americans depend on reliable and fast broadband internet to conduct their business everyday in the 21st century. 

Yet, despite this necessity, millions of Americans have little to no access to broadband internet, most of them in rural areas where Internet Service Providers deem it unprofitable to provide broadband service [@fingas]. A lack of fast broadband Internet also means a lack of new business investment in the community, as most modern businesses require fast, reliable internet just to run, causing many rural communities to take things into their own hands [@kang]. 

These issues are magnified by the gross inaccuracies often found on reports analyzing broadband connectivity, creating little motivation by policy makers to fix things [@lenz]. This, and other factors like unaffordable broadband prices, exacerbates inequality, by restricting opportunities for communication, education, and employment to those who need them most, like unemployed citizens [@fingas]. 

## Data
| Name/Link                          | Rows      | Vars  | Unit          |
|------------------------------------|-----------|-------|---------------|
| [ConnectBoulder Wi-Fi Usage](http://data.opencolorado.org/dataset/boulder-connect-boulder-wifi-usage)         | 4,517,064 | 15    | Wi-Fi Session |
| [NYS Broadband Availability](https://data.ny.gov/Economic-Development/Broadband-Availability-By-Municipality/sjc6-ftj4)         | 1,635       | 24    | Municipality  |
| [People Without Internet](https://www.kaggle.com/madaha/people-without-internet)            | 821        | 23    | Municipality  |
| [Urban Rate Broadband Survey](https://public.opendatasoft.com/explore/dataset/urban-rate-broadband-survey/table/)        | 9,122     | 14    | ISP in Market |
| [Gaming, Jobs, and Broadband Survey](http://www.pewinternet.org/dataset/june-2015-gaming-jobs-broadband/) | 2,001      | 140   | Person        |

## Works Cited